// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1ah_3tH3zGJZXWNyCd8KKhEZLTXHGajw',
    appId: '1:688828857002:web:a0f924e27a655712c86ed3',
    messagingSenderId: '688828857002',
    projectId: 'movie-list-bdad6',
    authDomain: 'movie-list-bdad6.firebaseapp.com',
    storageBucket: 'movie-list-bdad6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNNsyxQBmxySq331gF3KvDvGX29luCXio',
    appId: '1:688828857002:android:94e68bd4ec730ed8c86ed3',
    messagingSenderId: '688828857002',
    projectId: 'movie-list-bdad6',
    storageBucket: 'movie-list-bdad6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA554FHgTni7WNF-PV4sSWmc3lgL9KU4Mg',
    appId: '1:688828857002:ios:249b928e84e81bd0c86ed3',
    messagingSenderId: '688828857002',
    projectId: 'movie-list-bdad6',
    storageBucket: 'movie-list-bdad6.appspot.com',
    iosClientId: '688828857002-099kib2l5q436c0brua4251n0g3kqith.apps.googleusercontent.com',
    iosBundleId: 'id.ac.bsi.movielist',
  );
}
